services:
 ollama:
   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
   container_name: ollama
   pull_policy: always
   tty: true
   volumes:
     - ollama:/root/.ollama
   ports:
     - "11434:11434"
   restart: unless-stopped
   # GPUを使用する場合、以下の行のコメントを外してください
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]

 open-webui:
   image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
   container_name: open-webui
   pull_policy: always
   volumes:
     - open-webui:/app/backend/data
   ports:
     - ${OPEN_WEBUI_PORT-3000}:8080
   environment:
     - OLLAMA_BASE_URL=http://ollama:11434
   restart: unless-stopped
   depends_on:
     ollama:
       condition: service_started

volumes:
 ollama:
 open-webui:
